service: authguard-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  stage: dev

  environment:
    NODE_ENV: production
    PORT: 3000
    AWS_REGION: eu-north-1
    AWS_COGNITO_CLIENT_ID: 146m3ubtf0sntj5bv7lnt44rom
    AWS_COGNITO_AUTH_FLOW: USER_PASSWORD_AUTH
    AWS_COGNITO_USER_POOL_ID: eu-north-1_uV6yZFtMt

functions:
  api:
    handler: dist/main.handler
    timeout: 30
    memorySize: 512
    events:
      - httpApi: '*'

plugins:
  - serverless-offline

package:
  individually: true
  patterns:
    - '!node_modules/.prisma/**'
    - '!src/**'
    - 'dist/**'
    - 'node_modules/**'
